language: python
sudo: false
# Add or remove version for match with Travis support
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
os:
  - linux
env:

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: ENV=lint
      before_script: TOX_ENV=lint
    - python: 2.7
      sudo: true
      env: ENV=docs
      before_script: TOX_ENV=docs-travis
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y graphviz
      # Trigger ReadTheDocs build
      after_success: ./contrib/trigger_rtd_build.py 8284

addons:
  apt:
    packages:
      - graphviz  # needed for embedded graphs in the docs

install:
  - pip install --upgrade "pip<8.0.0"
  - pip install "virtualenv<14.0.0"
  - pip install "tox>=2.3.0,<2.4"
  - TOX_ENV=py$TRAVIS_PYTHON_VERSION

script:
  - tox -e $TOX_ENV

notifications:
  # Disabled until ASF switches to new mailing list software
  # when we can whitelist addresses
  #email:
  #  - "notifications@libcloud.apache.org"
  irc:
    - "chat.freenode.net#libcloud"
