language: python
# Add or remove version for match with Travis support
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - "pypy"
os:
  - linux
  # Note: OS X has been broken on Travis for a long time
  #- osx
env:

matrix:
  fast_finish: true
  include:
    - sudo: required
      python: 2.7
      env: ENV=lint
      before_script: TOX_ENV=lint
    - sudo: required
      python: 2.7
      env: ENV=docs
      before_script: TOX_ENV=docs-travis
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y graphviz
      # Trigger ReadTheDocs build
      after_success: ./contrib/trigger_rtd_build.py 8284

install:
  - TOX_ENV=py$TRAVIS_PYTHON_VERSION
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  # Disabled until ASF switches to new mailing list software
  # when we can whitelist addresses
  #email:
  #  - "notifications@libcloud.apache.org"
  irc:
    - "chat.freenode.net#libcloud"
