[tool.black]
max-line-length = 100
target_version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.virtualenv
    | __pycache__
  )/
)
'''

[tool.isort]
profile = "hug"
src_paths = ["libcloud", "contrib", "docs", "demos", "pylint_plugins"]
line_length = 100
indent = "    "
skip_glob = [".venv/*", ".tox/*", ".github/actions/*"]
length_sort = true
