name: CI

on: [push]

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python_version: [2.7, 3.4, 3.5, 3.6, 3.7, pypy, pypy3]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@master
    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python_version }}
    - name: Install OS / deb dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq gcc libvirt-dev
    - name: Install Python Dependencies
      run: |
        pip install "tox==3.12.1"
    - name: Run tox target
      run: |
        tox -e py${{ matrix.python_version }}

  lint_checks:
    name: Run various lint checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: [2.7]

    steps:
    - uses: actions/checkout@master
    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python_version }}
    - name: Install Python Dependencies
      run: |
        pip install "tox==3.12.1"
    - name: Run Checks
      run: |
        tox -e checks,lint,pylint

  docs:
    name: Build and upload Documentation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: [3.5]

    steps:
    - uses: actions/checkout@master
    - name: Use Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python_version }}
    - name: Install OS / deb dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq graphviz gcc libvirt-dev
    - name: Install Python Dependencies
      run: |
        pip install "tox==3.12.1"
    - name: Build Docs
      run: |
        tox -e docs-travis
    - name: Trigger ReadTheDocs build
      run: |
        echo "todo"
